export interface PropPlannerInputs {
  avgProfit: number;
  avgLoss: number;
  tradingDaysPerMonth: number;
  winRate: number;
  directToFunded: boolean;
  profitSplit: number;
  consistencyEnabled: boolean;
  consistencyPct: number;
  accountCount: number;
  scalingPlanPct: number;
  accountFeeRecurring: boolean;
  accountFeeAmount: number;
  activationEnabled: boolean;
  activationFeeAmount: number;
  evalProfitTarget: number;
  bufferAmount: number;
  firstPayout: number;
  recurringPayout: number;
  maxDrawdown: number;
}

export interface PropPlannerResults {
  tradingDaysPerMonth: number;
  tradingDaysPerYear: number;
  scalingPlanPct: number;
  fundedScale: number;
  profitFunded: number;
  lossFunded: number;
  evPerAccount: number;
  evPerAccountFunded: number;
  netDailyPerAccountEval: number;
  netDailyPerAccountFunded: number;
  tradingDailyTotal: number;
  tradingMonthlyTotal: number;
  tradingAnnualTotal: number;
  tradingMonthlyTotalEval: number;
  recurringCostMonthly: number;
  evalDaysPass: number | null;
  evalSubBillPeriods: number;
  evalSubCostDuringEval: number;
  feeCompareMonthly: number;
  afterRecurringMonthly: number;
  activationPerAccount: number;
  oneTimeEvalPerAccount: number;
  oneTimeEvalTotal: number;
  activationPassTotal: number;
  daysToFirstFunded: number | null;
  daysToRecurringFunded: number | null;
  netFirstPerAcc: number;
  netRecPerAcc: number;
  subCostPerAccEval: number | null;
  negativeTrading: boolean;
  negativeTradingEval: boolean;
  negativeAfterRecurring: boolean;
  showFeeMonthly: boolean;
  showFeeEvalRecurring: boolean;
  showFeeOneTimeEval: boolean;
  showFeeActivation: boolean;
  showFeeRollup: boolean;
  showPlanEval: boolean;
  showPlanEvalMonths: boolean;
  showPlanFunded: boolean;
  showPlanPath: boolean;
  feeWarnMsg: string;
  consistencyAlertHtml: string | null;
  consecutiveLossesText: string;
  evalTimelineHtml: string;
  firstTimelineHtml: string;
  recurringTimelineHtml: string;
  netSplitCaption: string;
  accountTypeNote: string;
  resultsBreakdownNote: string;
  timelineBannerHtml: string;
  keyLegendHtml: string;
  footerHtml: string;
  dashboardNote: string;
  netSplitSectionLabel: string;
}
